---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in wchrisjohnson-ansible-mac/playbook.yml"

    - name: install apps from pip
      pip: name={{item}}
      sudo: yes
      with_items:
          - virtualenv

    - name: install apps from homebrew
      sudo: false
      homebrew: name={{item}} state=present update_homebrew=yes
      with_items:
          - coreutils
          - git
          - wget
          - httpie
          - htop-osx
          - tree
